# Generated by Django 4.1.1 on 2023-03-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_deal_amount_deal_company_deal_status_task_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contact'),
        ),
    ]
