# Generated by Django 4.1.1 on 2023-03-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='value',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
